apiVersion: v1
kind: Service
metadata:
  name: jenkins-exam-client-service
spec:
  type: NodePort
  selector:
    app: jenkins-exam-client
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
      nodePort: 30001
